---
- name: Pull Docker Image of Calculator
  hosts: localhost
  vars:
    ansible_python_interpreter: /etc/bin/python3.8
  tasks:
    - name: Pull Image
      docker_image:
        name: dolo650/calculator
        source: pull
    - name: Start Docker Service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name Calculator dolo650/calculator
      
