---
- name: Pull Docker Image of Calculator
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: dolo650/calculator:latest
        source: pull
    - name: Start docker service
      ansible.windows.win_command: Start-Service docker
    - name: Running container
      shell: docker run -it -d --name Calculator dolo650/calculator